package settings
//
//var SERVER_ADDR          = "127.0.0.1"
var SERVER_ADDR          = "10.10.111.143"
var SERVER_PROTO         = "http"
var SERVER_PORT          = "8090"
var SERVER_URL           = SERVER_PROTO+"://"+SERVER_ADDR+":"+SERVER_PORT
//var RESTAPI_SERVER_ADDR  = "127.0.0.1"
var RESTAPI_SERVER_ADDR  = "10.10.111.143"
var RESTAPI_SERVER_PROTO = "http"
var RESTAPI_SERVER_PORT  = "9000"
var RESTAPI_URL          = RESTAPI_SERVER_PROTO+"://"+RESTAPI_SERVER_ADDR+":"+RESTAPI_SERVER_PORT

